{
    "name": "BinaryGuard Service Contracts",
    "version": "19.0.1.0.0",
    "summary": "Service agreements, maintenance contracts and SLA tracking",
    "author": "BinaryGuard Innovations Inc.",
    "website": "https://binaryguard.ca",
    "category": "Services/Contracts",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "sale",
        "project",
        "account",
        "binaryguard_core",
        "binaryguard_sales",
        "binaryguard_projects",
        "binaryguard_field_service",
        "binaryguard_helpdesk",
        "binaryguard_assets",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/contract_sequence.xml",
        "views/service_contract_views.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
