name: Deploy Odoo Production

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to DigitalOcean Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Droplet and
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT }}
          script: |
            sudo /usr/local/bin/deploy-odoo
